services:
  db-cw-app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - main_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://main_db:5432/main_db
      SPRING_DATASOURCE_USERNAME: ${MAIN_DB_USERNAME:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${MAIN_DB_PASSWD:-postgres}
    networks:
      - my_network

  main_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: main_db
      POSTGRES_USER: ${MAIN_DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${MAIN_DB_PASSWD:-postgres}
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - pg_data:/var/lib/postgresql/data

networks:
  my_network:
    driver: bridge

volumes:
  pg_data:
  app_backups:
